---
openapi: 3.0.0
info:
  title: libAPI
  description: API de livres crées dans le cadre du cours
  version: 1.0.0
servers:
- url: http://localhost/serviceWeb/servicesWeb/
paths:
  /allbooks:
    get:
      tags:
      - Livre
      summary: Affiche tous les livres.
      responses:
        "200":
          description: un tableau de livres
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Livres'
  /books/{id}:
    get:
      tags:
      - Livre
      summary: Affiche un livre selon son id.
      parameters:
      - name: id
        in: path
        description: Le id du livre à afficher
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Le livre à afficher
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Livre'
  /books/add:
    post:
      tags:
      - Livre
      summary: Crée un livre.
      requestBody:
        description: Les informations du livre à créer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
        required: true
      responses:
        "201":
          description: Le id du livre créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
components:
  schemas:
    Livre:
      required:
      - genreId
      - isbn
      - titre
      type: object
      properties:
        id:
          type: integer
          format: int64
        genreId:
          type: integer
          format: int64
        titre:
          type: string
        isbn:
          type: string
      example:
        id: 1
        genreId: 1
        titre: Fondation
        isbn: "9782070463619"
    Livres:
      type: array
      items:
        $ref: '#/components/schemas/Livre'
    body:
      type: object
      properties:
        genreId:
          type: integer
        titre:
          type: string
        isbn:
          type: string
      example:
        genreId: 1
        titre: Fondation
        isbn: "9782070463619"
    inline_response_201:
      type: object
      properties:
        books_id:
          type: integer
      example:
        books_id: 1
